language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "3.5-dev"
  - "nightly"
  - pypy
matrix:
  allow_failures:
    - python: 2.6
    - python: "3.5-dev"
    - python: "nightly"
    - python: pypy
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - build-essential
install:
  - "pip install coverage"
  - "travis_wait pip install -r requirements.txt"
script: nosetests tests --with-coverage --cover-package=lspopt
